### ISSUE TITLE
Undefined method `filter_map' for Array on Rails 6+ & Ruby < 2.7

### ISSUE THREAD

**Issue by spejamchr** [test-prof/test-prof#298]
### Tell us about your environment

**Ruby Version:** `2.6.7`

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** RSpec

**TestProf Version:** `1.3.3`

### What did you do?

I upgraded Rails from 5 -> 6

### What did you expect to happen?

I expected test-prof to continue working.

### What actually happened?

I got:

```
NoMethodError:
         undefined method `filter_map' for #<Array:0x00005562a68ce048>
         Did you mean?  filter
       # /home/runner/work/exec_online/exec_online/vendor/bundle/ruby/2.6.0/gems/test-prof-1.3.3/lib/test_prof/before_all/adapters/active_record.rb:13:in `all_connections'
```

Looks like [this check](https://github.com/test-prof/test-prof/blob/v1.3.3/lib/test_prof/before_all/adapters/active_record.rb#L12) tests for Rails 6+, and then [this line](https://github.com/test-prof/test-prof/blob/v1.3.3/lib/test_prof/before_all/adapters/active_record.rb#L13) uses the Ruby 2.7+ `filter_map` method, even though the required ruby version is [`>= 2.5.0`](https://github.com/test-prof/test-prof/blob/v1.3.3/test-prof.gemspec#L34).

**Comment by palkan** [comment]
Thanks for the report!

We've already stopped supporting Ruby <2.7 on master (so, 1.4+ won't work on 2.6), so it's better to upgrade. For now, I fixed this incompatibility and pushed v1.3.3.1.
